package pl.edu.pw.ee.petclinic.domain.doctor.enums;

public enum Specialization {
  GENERAL_PRACTICE,
  SURGERY,
  INTERNAL_MEDICINE,
  RADIOLOGY,
  DENTISTRY,
  CARDIOLOGY,
  ONCOLOGY,
  NEUROLOGY,
  OPHTHALMOLOGY,
  DERMATOLOGY,
  ANESTHESIOLOGY,
  PATHOLOGY,
  ZOOLOGY,
  WILDLIFE_MEDICINE,
  AVIAN_MEDICINE,
  EQUINE_MEDICINE,
  EXOTIC_ANIMALS,
}
